
const GET_ALL_APPLICATIONS = "";

const GET_APPLICATION_BY_ID = "";

const CREATE_APPLICATION = "";

const UPDATE_APPLICATION = "";

const DELETE_APPLICATION = "";

module.exports = {
    GET_ALL_APPLICATIONS,
    GET_APPLICATION_BY_ID,
    CREATE_APPLICATION,
    UPDATE_APPLICATION,
    DELETE_APPLICATION
}