
const GET_ALL_NOTIFICATIONS = "";

const GET_NOTIFICATION_BY_ID = "";

const CREATE_NOTIFICATION = "";

const UPDATE_NOTIFICATION = "";

const DELETE_NOTIFICATION = "";

module.exports = {
    GET_ALL_NOTIFICATIONS,
    GET_NOTIFICATION_BY_ID,
    CREATE_NOTIFICATION,
    UPDATE_NOTIFICATION,
    DELETE_NOTIFICATION
}